#!/bin/bash

# An error handling script

# Handle flags
# Not used right now, TODO, add more flags
handle_flags()
{
while [ "$1" != "" ]; do
  case $1 in
    -h | --help )   usage;
                    exit ;;
    * )             echo "That is not a valid argument.
                    Use -h or --help for usage."
  esac
  shift
done
}

error_exit()
{
  if [ "$1" != "" ]; then
    # look for help flag, but only look in the first position
    # this behavior might change.
    case $1 in
      -h | --help )   usage;
        exit ;;
      # Case wasn't help, print error
      * )             printf "$1" 1>&2
                      shift
    esac
    # Print all error message until end
    while [ "$1" != "" ]; do
      printf " ${1}" 1>&2
      shift
    done
    echo ""
    exit 1
  else 
    echo "Unknown Error" 1>&2
  fi
}

usage()
{
  echo "
  ##############################################
  An error handling script for shell executables.
  ##############################################


  Usage example:

  > if [ error ]
  >  echo error_exit <Debugging message>
  > fi


  * Adaptation of ©2000-2015, William E. Shotts, Jr
  * via http://linuxcommand.org/lc3_wss0140.php" 
}



# MAIN
echo ""
printf "ERROR:: "
error_exit $1

# Adaptation of ©2000-2015, William E. Shotts, Jr
# via http://linuxcommand.org/lc3_wss0140.php
